# -*- coding: utf-8 -*-
"""
Inställningar för Homevolt Batteri-optimerare (v3.0)
"""

# --- API & DATUM ---
PRICE_AREA = "SE3"
TARGET_DATE_STR = "2025-11-21"

# --- LIVE OVERRIDES ---
OPTIMIZE_FROM_TIME = "07:00"
OPTIMIZE_OVERRIDE_CURRENT_SOC_KWH = 12.2

# --- STRATEGI & FUNKTIONER (NYTT) ---
# Sätt till False för att stänga av all aktiv köp/sälj-optimering.
# Då fokuserar systemet ENBART på att kapa effekttoppar och hålla batteriet vid liv.
ENABLE_ARBITRAGE = False

# --- OPTIMERINGSMÅL ---
PREVIOUS_MONTHLY_HOUR_PEAK_POWER_KW = 1.01

# --- SCHEMAN ---
CONSUMPTION_SCHEDULE_RAW = {
    "07:00": 1700,
    "09:30": 1200,
    "12:30": 1000,
    "15:00": 1250
}

SOLAR_PRODUCTION_SCHEDULE_RAW = {
    "07:00": 0,
    "08:00": 0,
    "12:00": 0,
    "15:00": 0
}

# --- BATTERI-SPECIFIKATIONER ---
BATTERY_CAPACITY_KWH = 12.2
BATTERY_ENERGY_WH = BATTERY_CAPACITY_KWH * 1000
START_BATTERY_WH = BATTERY_ENERGY_WH 

# --- HÅRDVARUBEGRÄNSNINGAR ---
MAX_BATTERY_OUTPUT_W = 6000.0 
MAX_BATTERY_OUTPUT_PER_QUARTER_WH = MAX_BATTERY_OUTPUT_W / 4.0

LOW_SOC_THROTTLE_PERCENT = 15.0 
LOW_SOC_THROTTLE_WH = BATTERY_ENERGY_WH * (LOW_SOC_THROTTLE_PERCENT / 100.0)
LOW_SOC_MAX_OUTPUT_W = 400.0
LOW_SOC_MAX_OUTPUT_PER_QUARTER_WH = LOW_SOC_MAX_OUTPUT_W / 4.0

# --- KOSTNADER & AVGIFTER ---
ADDITIONAL_FEES_TAX_ORE = 60.0
ADDITIONAL_FEES_GRID_ORE = 8.0

GRID_SETPOINT_BIAS_W = 250.0
BIAS_WH_PER_QUARTER = GRID_SETPOINT_BIAS_W / 4.0

# --- SÄKERHETSMARGINALER ---
MIN_BATTERY_BUFFER_PERCENT = 5.0 
MIN_BATTERY_BUFFER_WH = BATTERY_ENERGY_WH * (MIN_BATTERY_BUFFER_PERCENT / 100.0)
HOUSE_CONSUMPTION_FUDGE_FACTOR = 1.1

EXPECTED_TOTAL_CONSUMPTION_KWH = 12.0 
CONSUMPTION_SANITY_TOLERANCE_PCT = 30.0 

TRY_KEEP_HOURS_BELOW_WH = None

MIN_PRICE_DIFF_ORE_FOR_SELLING = 50
DEFAULT_INITIAL_PRICE_ORE = 100 + (ADDITIONAL_FEES_TAX_ORE + ADDITIONAL_FEES_GRID_ORE)
BATTERY_CYCLE_COST_ORE = 25.0

# --- TIDSINSTÄLLNINGAR ---
SIMULATION_START_TIME_DEFAULT = "07:00"
SIMULATION_END_TIME = "19:00"

NIGHT_CHARGE_WINDOW_START = "00:00"
NIGHT_CHARGE_WINDOW_END = "07:00" 
CHARGE_DURATION_HOURS = 2.5

# --- VISUELLT ---
USE_COLORED_OUTPUT = True
SHOW_DETAILED_TABLE = True  # Sätt till False för att dölja kvartstabellen